import io
import pandas as pd
from typing import Tuple
from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from app.models.models import User, Transaction, Budget, Goal, BankAccount

def generate_pdf_report(db: Session, user: User, report_type: str = "monthly") -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=15
    )
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=12,
        spaceAfter=8
    )

    # Document Header
    now_str = datetime.now().strftime("%B %d, %Y")
    story.append(Paragraph(f"IntelliWealth Financial Report - {report_type.upper()}", title_style))
    story.append(Paragraph(f"Generated for {user.name} ({user.email}) on {now_str}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=15))

    # User Summary Cards Table
    total_income = db.query(func.sum(Transaction.amount)).filter(
        Transaction.user_id == user.id,
        Transaction.type == "Income"
    ).scalar() or 0.0

    total_expense = db.query(func.sum(Transaction.amount)).filter(
        Transaction.user_id == user.id,
        Transaction.type == "Expense"
    ).scalar() or 0.0

    net_savings = total_income - total_expense
    savings_rate = (net_savings / total_income * 100) if total_income > 0 else 0.0

    summary_data = [
        ["Monthly Income", "Total Expenses", "Net Savings", "Savings Rate"],
        [f"₹{total_income:,.2f}", f"₹{total_expense:,.2f}", f"₹{net_savings:,.2f}", f"{savings_rate:.1f}%"]
    ]

    t_summary = Table(summary_data, colWidths=[130, 130, 130, 130])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 15))

    # Recent Transactions Table
    story.append(Paragraph("Recent Transactions Audit", section_heading))
    txs = db.query(Transaction).filter(Transaction.user_id == user.id).order_by(Transaction.date.desc()).limit(15).all()

    tx_table_data = [["Date", "Merchant", "Category", "Type", "Amount"]]
    for t in txs:
        tx_table_data.append([
            t.date,
            t.merchant[:20],
            t.category,
            t.type,
            f"₹{t.amount:,.2f}"
        ])

    if len(tx_table_data) > 1:
        t_tx = Table(tx_table_data, colWidths=[80, 160, 110, 80, 90])
        t_tx.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#334155")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(t_tx)

    # Footer Notice
    story.append(Spacer(1, 20))
    story.append(Paragraph("End of Report. Confidential - Generated by IntelliWealth Financial Intelligence Platform.", subtitle_style))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

def generate_csv_report(db: Session, user: User) -> str:
    txs = db.query(Transaction).filter(Transaction.user_id == user.id).order_by(Transaction.date.desc()).all()
    data = [
        {
            "Transaction ID": t.id,
            "Date": t.date,
            "Merchant": t.merchant,
            "Amount": t.amount,
            "Type": t.type,
            "Category": t.category,
            "Payment Method": t.payment_method,
            "Notes": t.notes or "",
            "Categorizer": t.categorizer_type
        }
        for t in txs
    ]
    df = pd.DataFrame(data)
    return df.to_csv(index=False)
